# Generated by Django 3.2.16 on 2023-09-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Historique_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_avant', models.CharField(blank=True, db_column='Before_value', default='', max_length=1024, null=True, verbose_name='Valeur Avant')),
                ('valeur_apres', models.CharField(blank=True, db_column='After_value', default='', max_length=1024, null=True, verbose_name='Valeur Apres')),
                ('modele', models.CharField(db_column='model', default='', max_length=1024, verbose_name='Modele')),
                ('auteur', models.CharField(db_column='autor', default='', max_length=1024, verbose_name='Auteur')),
                ('etat', models.CharField(blank=True, db_column='state', max_length=50, null=True, verbose_name='Etat')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='created_date', verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='updated_date', verbose_name='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Historique Action',
                'verbose_name_plural': 'Historiques Actions',
                'db_table': 'sup_action_story',
            },
        ),
        migrations.CreateModel(
            name='Model_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erreur', models.CharField(db_column='error', default='', max_length=1024, verbose_name='Erreur')),
                ('modele', models.CharField(db_column='model', default='', max_length=1024, verbose_name='Modele')),
                ('auteur', models.CharField(db_column='autor', default='', max_length=1024, verbose_name='Auteur')),
                ('etat', models.CharField(blank=True, db_column='state', max_length=50, null=True, verbose_name='Etat')),
                ('creation_date', models.DateTimeField(auto_now_add=True, db_column='created_date', verbose_name='Date de création')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='updated_date', verbose_name='Date de dernière modification')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'sup_logs',
            },
        ),
    ]
